# Generated by Django 3.2.6 on 2021-10-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forwardfile',
            options={'ordering': ['-forwarded_at']},
        ),
        migrations.AddField(
            model_name='forwardfile',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forwardfile',
            name='forwarded',
            field=models.BooleanField(default=False),
        ),
    ]
