# Generated by Django 3.2.6 on 2021-09-08 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forwardfile',
            name='sender',
        ),
        migrations.AddField(
            model_name='forwardfile',
            name='receiver',
            field=models.CharField(choices=[('manager', 'Manager'), ('cm', 'Cm'), ('ceo', 'Ceo'), ('stores', 'Stores')], default='manager', max_length=30),
        ),
        migrations.AlterField(
            model_name='forwardfile',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
