# Generated by Django 3.2.6 on 2021-09-15 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doc', '0002_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='members',
        ),
        migrations.AddField(
            model_name='department',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
