# Generated by Django 3.2.6 on 2021-09-09 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doc', '0004_auto_20210908_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forwardfile',
            name='receivers',
        ),
        migrations.AddField(
            model_name='forwardfile',
            name='receiver',
            field=models.ManyToManyField(related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
