# Generated by Django 3.2.6 on 2021-09-09 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doc', '0005_auto_20210909_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forwardfile',
            name='receiver',
        ),
        migrations.AddField(
            model_name='forwardfile',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='core.user'),
            preserve_default=False,
        ),
    ]
