# Generated by Django 3.2.6 on 2021-09-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usertype_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
